{% set version = "1.0.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rbiom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rbiom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rbiom/rbiom_{{ version }}.tar.gz
  sha256: 8f7d1c380148022ea677066fd57757a967eff1ac36cfb82b827f913b7450d58e

build:
  merge_build_host: true  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-r.utils
    - r-rcpp
    - r-rcppparallel
    - r-magrittr
    - r-openxlsx
    - r-plyr
    - r-rjson
    - r-slam

  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-r.utils
    - r-rcpp
    - r-rcppparallel
    - r-magrittr
    - r-openxlsx
    - r-plyr
    - r-rjson
    - r-slam

test:
  commands:
    - $R -e "library('rbiom')"           # [not win]
    - "\"%R%\" -e \"library('rbiom')\""  # [win]

about:
  home: https://cmmr.github.io/rbiom/index.html

  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3

  summary: A toolkit for working with Biological Observation Matrix ('BIOM') files. Features include reading/writing all 'BIOM' formats, rarefaction, alpha diversity, beta diversity (including 'UniFrac'), summarizing counts by taxonomic level, and sample subsetting. Standalone functions for reading, writing, and subsetting
    phylogenetic trees are also provided. All CPU intensive operations are encoded in C with multi-thread support.

extra:
  recipe-maintainers:
    - conda-forge/r
    - dansmith01
