{% set version = "2.0.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rbiom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rbiom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rbiom/rbiom_{{ version }}.tar.gz
  sha256: 46f97cda4abccb4d48c9daac867ebf203bfba70976b8a48b2026c361156b9444

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-rcppthread               # [build_platform != target_platform]
    - r-ape                      # [build_platform != target_platform]
    - r-broom                    # [build_platform != target_platform]
    - r-cluster                  # [build_platform != target_platform]
    - r-dplyr                    # [build_platform != target_platform]
    - r-emmeans                  # [build_platform != target_platform]
    - r-fillpattern              # [build_platform != target_platform]
    - r-ggnewscale               # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-ggtext                   # [build_platform != target_platform]
    - r-jsonlite                 # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-mgcv                     # [build_platform != target_platform]
    - r-pillar                   # [build_platform != target_platform]
    - r-plyr                     # [build_platform != target_platform]
    - r-readr                    # [build_platform != target_platform]
    - r-readxl                   # [build_platform != target_platform]
    - r-slam                     # [build_platform != target_platform]
    - r-tidyplots                # [build_platform != target_platform]
    - r-vegan                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcppthread
    - r-ape
    - r-broom
    - r-cluster
    - r-dplyr
    - r-emmeans
    - r-fillpattern
    - r-ggnewscale
    - r-ggplot2
    - r-ggtext
    - r-jsonlite
    - r-magrittr
    - r-mgcv
    - r-pillar
    - r-plyr
    - r-readr
    - r-readxl
    - r-slam
    - r-tidyplots
    - r-vegan
  run:
    - r-base
    - r-rcpp
    - r-rcppthread
    - r-ape
    - r-broom
    - r-cluster
    - r-dplyr
    - r-emmeans
    - r-fillpattern
    - r-ggnewscale
    - r-ggplot2
    - r-ggtext
    - r-jsonlite
    - r-magrittr
    - r-mgcv
    - r-pillar
    - r-plyr
    - r-readr
    - r-readxl
    - r-slam
    - r-tidyplots
    - r-vegan

test:
  commands:
    - $R -e "library('rbiom')"           # [not win]
    - "\"%R%\" -e \"library('rbiom')\""  # [win]

about:
  home: https://cmmr.github.io/rbiom/, https://github.com/cmmr/rbiom
  license: MIT
  summary: A toolkit for working with Biological Observation Matrix ('BIOM') files. Read/write all 'BIOM' formats. Compute rarefaction, alpha diversity, and beta diversity (including 'UniFrac'). Summarize counts by taxonomic level. Subset based on metadata. Generate visualizations and statistical analyses. CPU intensive operations are coded in C++ for speed.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - dansmith01
